### ISSUE TITLE
Question on layouts

### ISSUE THREAD

**Issue by zzpixel** [FuryBaguette/SwitchLayoutEditor#15]
I dont know what any of the parts are for and how they display, I am really confused about it. Can someone please explain? 
![Screenshot 2020-12-10 210452](https://user-images.githubusercontent.com/73656838/101852343-6d668580-3b2b-11eb-8c44-14ff76e386a0.png) 
Theres aren't the only ones Im confused about.
Sorry if this is really stupid.

**Comment by exelix11** [comment]
Not really an editor issue, those are the internal file names.
Some are documented in the [mstaller wiki](https://github.com/exelix11/SwitchThemeInjector/wiki) unfortunately not many of them so you'll have to guess and experiment.
That seems to be the home menu so the main layout is rdtBase, inside of it there are prt1 panes, those reference the other files in the szs by name, that's how i figure them out.
