### ISSUE TITLE
How to change the up and down position?

### ISSUE THREAD

**Issue by tomxhachijuroku** [FuryBaguette/SwitchLayoutEditor#20]
Halo, love your work but I have a question I'm translating Detective Pikachu to Polish, and I need to edit the positions of letters left and right work, but up and down shows it works in the editor but in the game the letter I need to move up to match the rest is still in the wrong place I even tried that on switch toolbox and it's the same, what am I doing wrong, please help me it's drives me crazy:
![og position 1](https://user-images.githubusercontent.com/64981865/171228986-dadc28d1-9a1a-45c8-9cee-c5ac30a0b16a.png)
![og position 2](https://user-images.githubusercontent.com/64981865/171230863-81b04fe2-ac1f-4a37-ae5f-67504a91e91e.png)
After editing:
![ed position 1](https://user-images.githubusercontent.com/64981865/171229195-a792ba64-e109-4fe8-8768-b038363df497.png)
![ed position 2](https://user-images.githubusercontent.com/64981865/171230912-d3e1f1f5-aabd-4dd4-a111-c516704e14f5.png)

**Comment by exelix11** [comment]
Don't know, parent transformations can mess up the rendering of compoents but this doesn't seem to be the case, if switch toolbox has the same issue maybe it's something the game does on its own like some text wrapping behavior.

Maybe try to increase the size (not scale) of the container pane so if the game does bounds checks for the letters they will still be valid, if that doesn't work I don't think i'll be able to help you

**Comment by tomxhachijuroku** [comment]
YES! It worked:
![yes](https://user-images.githubusercontent.com/64981865/171418641-b25843b8-2185-4bd1-9318-2dc681808e8f.png)
Thanks for the advice, have a nice day!
