### ISSUE TITLE
Windows Defender detects this as a Trojan and prevents me from downloading.

### ISSUE THREAD

**Issue by IMPERIUSHAK** [FuryBaguette/SwitchLayoutEditor#28]
![Screenshot_1](https://github.com/FuryBaguette/SwitchLayoutEditor/assets/121381273/228c0335-1336-4c7d-bfd3-122d042b7b9d)

idk why but every time i upload my web project to github and want to download again this problems appears 
i tried reinstall windows  but it couldnt help but i dont have any thojans
(sry for my english)

**Comment by exelix11** [comment]
This has been an issue for a while, see https://github.com/FuryBaguette/SwitchLayoutEditor/issues/14 

My understanding is that [release 15](https://github.com/FuryBaguette/SwitchLayoutEditor/releases/tag/beta15) does not get detected, or at least i can download and launch it just fine.

Unfortunately it seems there is nothing i can do about it, if you don't trust the program either compile it on your PC or just run it in a VM like Windows Sandbox.
