### ISSUE TITLE
Can't edit the layout

### ISSUE THREAD

**Issue by ebiak** [FuryBaguette/SwitchLayoutEditor#4]
When i load a szs file it shows me all the bflyt files inside it but it doesn't show me the layout . Is there something wrong with what i do or its a bug?

**Comment by exelix11** [comment]
Double click any bflyt file to open it in the editor

**Comment by ebiak** [comment]
i can't thats the problem

**Comment by ebiak** [comment]
oh thanks i was trying to open the bflan files
